version: '3.3'

services: 
  banco_dados:
    build: ./database/.
    container_name: banco_dados
    hostname: banco_dados
    ports: 
      - "1433:1433"

  api:
    build: ./api
    container_name: api
    ports: 
      - "8081:8081"